default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  adapter: postgresql
  host: localhost
  username: root
  database: dz_development

test:
  <<: *default
  database: dz_test
