default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  host: localhost
  username: root
  database: dz_production

test:
  <<: *default
  database: dz_test

development:
  <<: *default
  database: dz_test
