default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

test:
  <<: *default
  database: dz_test

development:
  <<: *default
  database: dz_development

production:
  <<: *default
  database: db/production.postgresql
